### ISSUE TITLE
Using Fast-BVH in our project

### ISSUE THREAD

**Issue by EasternJournalist** [brandonpelfrey/Fast-BVH#25]
Hello! 
Fast-BVH is quite helpful! My teammates and I are currently working on a course project, *non-Euclidean Graphics*, which aims to discover the graphics in "twisted" non-Euclidean space where the curvatures are not zero (mertric are neither orthogonal or constant). Here is the link - https://github.com/fyr233/nonEuclidGraphics. 
We were seeking for a high-performance and easy-to-modify intersector library that could fit in our algorithm. And we find Fast-BVH very helpful. We modify only a few codes (to make it efficient for our goal specifically, quite short length of intersection testing is needed each in hundreds of millions of iterations).
We copied the all Fast-BVH files to `nonEuclidGraphics/include/_deps` for sake of convenience. We are now working intensely due to approaching project deadline. We would be very grateful if you would allow us to use Fast-BVH in our project. We would note our reference to Fast-BVH in our repository, report, demo video etc.

Thanks again!

**Comment by brandonpelfrey** [comment]
Glad it can be of use @EasternJournalist 😄 You do not have to ask for permission as the project is MIT licensed. Thank you for the mention in the project though! Let me know if you find things that could be improved.
