### ISSUE TITLE
Would you consider to add support on Windows Platform ?

### ISSUE THREAD

**Issue by ychding11** [brandonpelfrey/Fast-BVH#9]
- Write a CMakeLists.txt, use cmake to generate vs solution.
- implementation of Stopwatch, use stand one, for example, std::chrono::system_clock::now() in c++11.

**Comment by brandonpelfrey** [comment]
This is now using std::chrono and CMakeLists.txt is available. I cannot test if this would compile in VS C++. I am going to assume for now that this will build in Windows now. Feel free to open with a particular bug if it will not build.
